using System.ComponentModel.DataAnnotations;

namespace Yare.BlazorApp.Models.Enums;

public enum WatchBrand
{
    Accurist = 0,
    [Display(Name = "A. Favre & Fils")] AFavreAndFils,
    [Display(Name = "A.Lange & Söhne")] ALangeAndSöhne,
    AKRIVIA,
    Akrone,
    Alpina,
    [Display(Name = "Armand Nicolet")] ArmandNicolet,
    [Display(Name = "Arnold & Son")] ArnoldAndSon,
    [Display(Name = "Audemars Piguet")] AudemarsPiguet,
    [Display(Name = "Auguste Reymond")] AugusteReymond,
    [Display(Name = "Armani Exchange")] ArmaniExchange,
    Boss,
    BVLGARI,
    [Display(Name = "Backes & Strauss")] BackesAndStrauss,
    [Display(Name = "BALL Watch")] BallWatch,
    [Display(Name = "Baume & Mercier")] BaumeAndMercier,
    [Display(Name = "Bell & Ross")] BellAndRoss,
    Blancpain,
    Bomberg,
    Breguet,
    Breitling,
    Bremont,
    [Display(Name = "Carl F. Bucherer")] CarlFBucherer,
    Cartier,
    Certina,
    Chanel,
    Chopard,
    Chronoswiss,
    Corum,
    [Display(Name = "De Bethune")] DeBethune,
    Doxa,
    Ebel,
    OMEGA,
    [Display(Name = "TAG Heuer")] TAGHEUER,
    Hublot,
    Tudor,
    [Display(Name = "Girard-Perregaux")] GirardPerregaux,
    [Display(Name = "Jaeger-LeCoultre")] JaegerLeCoultre,
    Rolex,
    [Display(Name = "Patek Philippe")] PatekPhilippe,
    [Display(Name = "IWC Schaffhausen")] IWCSchaffhausen,
    Longines,
    Tissot,
    [Display(Name = "Vacheron Constantin")] VacheronConstantin,
}
